### ISSUE TITLE
Don't include AWS Access key and secret key in the code

### ISSUE THREAD

**Issue by qpleple** [constup/aws-secrets-bundle#1]
Hi,

Great idea for a bundle!

I'm not sure why you mention AWS_SECRET_ID and AWS_SECRET_STRING here:

https://github.com/constup/aws-secrets-bundle/blob/3bc8391efa927dbd4deecf41643fcb1c3865d715/src/Provider/AwsSecretsEnvVarProvider.php#L11-L12

and here:

https://github.com/constup/aws-secrets-bundle/blob/3bc8391efa927dbd4deecf41643fcb1c3865d715/src/AwsSecretsEnvVarProcessor.php#L14-L15

I don't think these constants should be anywhere in the code.

Cheers

Quentin

**Comment by constup** [comment]
You are right. It looks like `AwsSecretsEnvVarProcessor` doesn't need these constants. I'll fix that.

Regarding constants in general:

When working with arrays, I like to declare array keys as constants.

Benefits:

- Developers working on the project are less prone to errors caused by mistyping array keys in the code;
- Better code completion in IDEs, since you're typing names of constants when you'd like to use them;
- Better visibility of available array keys. You only need to type `self::` and IDE's code completion will already list available constants (array key values).

Downsides:

- Code obfuscation. You're not working with direct values, you're working with constants instead;
- A very slight performance impact.

**Comment by constup** [comment]
Obsolete constants in `AwsSecretsEnvVarProcessor` are now removed in 1.0.8 (commit: https://github.com/constup/aws-secrets-bundle/commit/0e4dcf1dc12b7ee490ac3219443c7c4bad477b03)
